#!/usr/bin/env php
<?php
    //User input
    $command = $argv[1] ?? null;

    switch ($command) {
        case 'add':
            $description = $argv[2] ?? '';
            $newTask = new Task($description);
            //Read existing tasks
            $tasks = [];

            if (file_exists("tasks.json")) {
                $json = file_get_contents("tasks.json");
                $tasks = json_decode($json, true) ?? [];
            }

            //Add new tasks
            $tasks[] = $newTask;

            //Save tasks
            file_put_contents("tasks.json", json_encode($tasks, JSON_PRETTY_PRINT));
            echo "Add: $description\n";
            break;

        case 'update':
            //Read tasks
            $tasks = [];
            if (file_exists("tasks.json")) {
                $json = file_get_contents("tasks.json");
                $tasks = json_decode($json, true) ?? [];    
            }
            //Update task description
            $index = $argv[2] ?? null;
            $description = $argv[3] ?? '';
            //Update task updatedAt
            $tasks[$index - 1]["description"] = $description;
            $tasks[$index- 1]["updatedAt"] = date("Y-m-d H:i:s");
            //Save tasks
            file_put_contents("tasks.json", json_encode($tasks, JSON_PRETTY_PRINT));
            break;

        case 'delete':
            //Read tasks
            $tasks = [];
            if (file_exists("tasks.json")) {
                $json = file_get_contents("tasks.json");
                $tasks = json_decode($json, true) ?? [];
            }

            $index = $argv[2] ?? null;
            //Delete task
            array_splice($tasks, $index - 1, 1);
            //Save tasks
            file_put_contents("tasks.json", json_encode($tasks, JSON_PRETTY_PRINT));
            break;

        case 'list':
            //Read tasks
            $tasks = [];
            if (file_exists("tasks.json")) {
                $json = file_get_contents("tasks.json");
                $tasks = json_decode($json, true) ?? [];
            }

            if (count($tasks) == 0) {
                echo "No tasks found\n";
            }

            $status = $argv[2] ?? null;

            if (!$status) {
            //Loop through ALL tasks
                foreach  ($tasks as $task) {
                    echo $task["description"] . "\n";
                }
            } else {
                //Loop by status
                foreach ($tasks as $task) {
                    if ($task["status"] === $status) {
                        echo $task["description"] . "\n";
                    }
                }
            }



            
            break;

        default:
            echo "Unknown command\n";
    }

    class Task {
        public $id;
        public $description;
        public $status;
        public $createdAt;
        public $updatedAt;

        function __construct ($description) {
            $this->id = uniqid();
            $this->description = $description;
            $this->status = "in-progress";
            $this->createdAt = date("Y-m-d H:i:s");
            $this->updatedAt = date("Y-m-d H:i:s");
        }
    }