#!/usr/bin/env php
<?php
    //Load tasks helper
    function loadTasks() {
        $tasks = [];
        if (file_exists("tasks.json")) {
            $json = file_get_contents("tasks.json");
            $tasks = json_decode($json, true) ?? [];
        }
        return $tasks;
    }

    //Save tasks helper
    function saveTasks($taskList) {
        file_put_contents("tasks.json", json_encode($taskList, JSON_PRETTY_PRINT));
    }

    //User input
    $command = $argv[1] ?? null;

    switch ($command) {
        case 'add':
            $description = $argv[2] ?? '';
            $newTask = new Task($description);
            //Read existing tasks
            $taskList = loadTasks();
            //Add new tasks
            $taskList[] = $newTask;
            //Save tasks
            saveTasks($taskList);
            echo "Add: $description\n";
            break;

        case 'update':
            //Read tasks
            $taskList = loadTasks();
            //Update task description
            $index = $argv[2] ?? null;
            $description = $argv[3] ?? '';
            //Update task updatedAt
            $taskList[$index - 1]["description"] = $description;
            $taskList[$index- 1]["updatedAt"] = date("Y-m-d H:i:s");
            //Save tasks
            saveTasks($taskList);
            break;

        case 'delete':
            //Read tasks
            $taskList = loadTasks();
            $index = $argv[2] ?? null;
            //Delete task
            array_splice($taskList, $index - 1, 1);
            //Save tasks
            saveTasks($taskList);
            break;

        case 'list':
            //Read tasks
            $taskList = loadTasks();
            if (count($taskList) == 0) {
                echo "No tasks found\n";
            }

            $status = $argv[2] ?? null;

            if (!$status) {
            //Loop through ALL tasks
                foreach  ($taskList as $task) {
                    echo $task["description"] . "\n";
                }
            } else {
                //Loop by status
                foreach ($taskList as $task) {
                    if ($task["status"] === $status) {
                        echo $task["description"] . "\n";
                    }
                }
            }
            break;

        default:
            echo "Unknown command\n";
    }

    class Task {
        public $id;
        public $description;
        public $status;
        public $createdAt;
        public $updatedAt;

        function __construct ($description) {
            $this->id = uniqid();
            $this->description = $description;
            $this->status = "in-progress";
            $this->createdAt = date("Y-m-d H:i:s");
            $this->updatedAt = date("Y-m-d H:i:s");
        }
    }